### PR TITLE
update ssh.crypto and other modules

### PR DESCRIPTION
**Pull request by heat1024**
## Overview

Update ssh crypto and other modules to latest.
The main perpose of this PR is fix https://github.com/tsurubee/sshr.crypto/pull/9 problem.

### CODE REVIEW

**Comment by heat1024** [comment]
@tsurubee 
I have created PR for sshr also! Plz review here too 😄

**Comment by tsurubee** [comment]
@heat1024 
Looks good! Thank you!!

**Comment by heat1024** [comment]
Thanks!
I'll push release tag by v0.1.9

**Comment by heat1024** [comment]
pushed https://github.com/tsurubee/sshr/releases/tag/v0.1.9

**Pull request merged**
